from . import views
from django.urls import path


urlpatterns = [
    path('', views.admin_login, name='admin_login'),
    path('admin_dash/', views.admin_dash, name='admin_dash'),
    path('admin_product/', views.admin_product, name='admin_product'),
    path('user_manage/', views.user_manage, name='user_manage'),
    path('add_user', views.add_user, name ='add_user'),
    path('update/<str:id>', views.update, name='update'),
    path('delete/<str:id>', views.delete, name='delete'),
    path('change_status/<str:id>', views.change_status, name='change_status'),
    path('admin_cat/', views.admin_cat, name='admin_cat'),
    path('add_cat', views.add_cat, name='add_cat'),
    path('update_cat/<str:id>', views.update_cat, name='update_cat'),
    path('block_cat/<str:id>', views.block_cat, name='block_cat'),
    path('add_prod', views.add_prod, name='add_prod'),
    path('update_prod/<str:id>', views.update_prod, name='update_prod'),
    path('delete_prod/<str:id>', views.delete_prod, name='delete_prod'),
    path('admin_variation/', views.admin_variation, name='admin_variation'),
    path('add_variation', views.add_variation, name='add_variation'),
    path('update_variation/<str:id>', views.update_variation, name='update_variation'),
    path('delete_variation/<str:id>', views.delete_variation, name='delete_variation'),
    path('admin_order/', views.admin_order, name='admin_order'),
    path('admin_order_detail/<str:order_id>', views.admin_order_detail, name='admin_order_detail'),
    path('change_order_status/<str:order_id>', views.change_order_status, name='change_order_status'),
    path('cancel_order_admin/<str:order_id>', views.cancel_order_admin, name='cancel_order_admin'),
    path('search_order/', views.search_order, name='search_order'),
    path('new_to_old/', views.new_to_old, name='new_to_old'),
    path('old_to_new/', views.old_to_new, name='old_to_new'),
    path('admin_logout/', views.admin_logout, name='admin_logout'),
    path('coupon_manage/', views.coupon_manage, name='coupon_manage'),
    path('create_coupon/', views.create_coupon, name='create_coupon'),
    path('edit_coupon/<str:coupon_id>', views.edit_coupon, name='edit_coupon'),
    path('delete_coupon/<str:coupon_id>', views.delete_coupon, name='delete_coupon'),
    path('cat_offer_manage/', views.cat_offer_manage, name='cat_offer_manage'),
    path('create_catoffer/', views.create_catoffer, name='create_catoffer'),
    path('edit_catoffer/<str:id>', views.edit_catoffer, name='edit_catoffer'),
    path('delete_catoffer/<str:id>', views.delete_catoffer, name='delete_catoffer'),
    path('min_offer_manage/', views.min_offer_manage, name='min_offer_manage'),
    path('create_minoffer/', views.create_minoffer, name='create_minoffer'),
    path('edit_minoffer/<str:id>', views.edit_minoffer, name='edit_minoffer'),
    path('delete_minoffer/<str:id>', views.delete_minoffer, name='delete_minoffer'),
    path('sales_report/', views.sales_report, name='sales_report'),
    path('pdf_view/', views.ViewPDF.as_view(), name="pdf_view"),
    path('pdf_download/', views.DownloadPDF.as_view(), name="pdf_download"),
    path('admin_lte/', views.admin_lte, name='admin_lte')
    
]
