# Generated by Django 4.2.3 on 2023-08-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_rename_discount_order_coupon_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Completed', 'Completed'), ('Cancelled', 'cancelled'), ('Accepted', 'Accepted')], default='New', max_length=10),
        ),
    ]
