# Generated by Django 4.2.3 on 2023-08-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_category_cat_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_status',
            field=models.BooleanField(default=True),
        ),
    ]
