# Generated by Django 4.2.3 on 2023-08-03 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_category_cat_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cat_status',
        ),
    ]
