# Generated by Django 4.2.3 on 2023-08-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_minimumpurchaseoffer_categoryoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='off_price',
            field=models.IntegerField(null=True),
        ),
    ]
