# Generated by Django 4.2.3 on 2023-08-17 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_product_off_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='off_price',
            new_name='new_price',
        ),
    ]
