# Generated by Django 4.2.3 on 2024-05-27 13:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_reviewrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='cat_image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='variant_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='variant_image'),
        ),
    ]
