# Generated by Django 4.2.3 on 2023-07-31 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_managers_remove_user_is_phone_verified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_verified',
            new_name='is_phone_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
